### ISSUE TITLE
Fix Nested For Loops

### ISSUE THREAD

**Issue by Ryan-Vreeke** [Ryan-Vreeke/Templar#12]
![image](https://github.com/user-attachments/assets/4276be4e-8e9f-4d5d-899d-b75f54ed5a16)
![image](https://github.com/user-attachments/assets/1e322a86-c4f8-4008-ba72-b8233100e59b)

**Comment by ryan-vreeke1** [comment]
I think this is an issue with the for syntax an parsing it. The parser is grabbing the inner for loops `}` and causing it to break. Consider changing the syntax to be `{{.for ()}} ..... {{/for}}` like handlebars
